name: Release
on:
  push:
    branches:
      - master

permissions:
  contents: read # for checkout

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '>=18.x.x'

      - name: Install dependencies, run eslint, tests and build
        run: |
          npm ci
          npm run lint
          npm run test:cov
          npm run build

      - name: Add extra files to dist
        run: cp package.json README.md dist/

      - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
        run: npm audit signatures

      - name: Publish NPM package
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          HUSKY: 0
        run: npx semantic-release

      - name: Update package.json and package-lock.json
        uses: oleksiyrudenko/gha-git-credentials@v2-latest
        with:
          token: '${{ secrets.GITHUB_TOKEN }}'
        run: |
          cp dist/package.json .
          npm i --package-lock-only
          git commit -a -m "chore(release): Update package*.json [skip ci]"
          git push -o ci.skip

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
